session_name: capp-rs
shell_command_before: "export RUST_LOG=info; clear"
windows:
  - window_name: code
    focus: true
    start-directory: ./
    panes:
      - shell_command:
        - helix
  - window_name: agent
    start-directory: ./
    panes:
      - shell_command:
        - codex
  - window_name: cmd1
    start-directory: ./
    panes:
      - shell_command:
        - clear
  - window_name: cmd2
    panes:
      - shell_command:
        # - emacs -nw notes.org
        - eza -l
  - window_name: yazi
    panes:
      - shell_command:
        - yazi
